"""Initial schema

Revision ID: 5a5618994701
Revises:
Create Date: 2026-08-07 13:35:50.080903

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a5618994701"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_email", sa.String(length=255), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column("api_key_prefix", sa.String(length=12), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "rate_limit_per_minute",
            sa.Integer(),
            server_default=sa.text("600"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rate_limit_per_minute > 0", name="ck_applications_rate_limit_positive"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_api_key_hash"),
        "applications",
        ["api_key_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_applications_owner_email"),
        "applications",
        ["owner_email"],
        unique=True,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("distinct_id", sa.String(length=128), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "char_length(event_name) > 0", name="ck_events_event_name_not_empty"
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_events_app_idempotency",
        "events",
        ["application_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "idx_events_app_name_time",
        "events",
        ["application_id", "event_name", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_events_metadata_gin",
        "events",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_events_application_id"), "events", ["application_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_application_id"), table_name="events")
    op.drop_index(
        "idx_events_metadata_gin", table_name="events", postgresql_using="gin"
    )
    op.drop_index("idx_events_app_name_time", table_name="events")
    op.drop_index(
        "idx_events_app_idempotency",
        table_name="events",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_table("events")
    op.drop_index(op.f("ix_applications_owner_email"), table_name="applications")
    op.drop_index(op.f("ix_applications_api_key_hash"), table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###
